name: Control
settings:
  DEVELOPMENT_TEAM: K78G42H4U2
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 0.1.0
options:
  bundleIdPrefix: com.joeblau
  deploymentTarget:
    macOS: "11.0"
  createIntermediateGroups: true
  preGenCommand: .github/scripts/pre.sh
  postGenCommand: .github/scripts/post.sh
packages:
  swift-composable-architecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.9.0
  composable-core-location:
    url: https://github.com/pointfreeco/composable-core-location
    from: 0.1.0
targets:
  Control:
    type: application
    platform: macOS
    sources:
      - path: Control
        excludes:
          - Control/PreviewContent/*
      - path: Control/Resources/
        buildPhase: resources
    settings:
      DEVELOPMENT_ASSET_PATHS: Control/PreviewContent
      PRODUCT_BUNDLE_IDENTIFIER: com.joeblau.Control
      CODE_SIGN_ENTITLEMENTS: Control/SupportingFiles/Control.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: composable-core-location
        product: ComposableCoreLocation